import Header from "@/components/Header/Header";
import type { Metadata } from "next";
import "./globals.scss";
import { libreWithText, texturina } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={texturina.className}>
        <Header className={libreWithText.className} />
        {children}
      </body>
    </html>
  );
}
